apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: default
  labels:
    tier: backend
spec:
  selector:
    app: nginx
    tier: backend
  ports:
  - port: 8080
    targetPort: 443
    name: https
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default
  labels:
    app: nginx
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
      tier: backend
  template:
    metadata:
      labels:
        app: nginx
        tier: backend
    spec:
      containers:
      - name: nginx
        image: nginx:1.18-alpine
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        - containerPort: 443
          name: https
          protocol: TCP
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        - name: nginx-secret-volume
          mountPath: /etc/nginx/tls/

      volumes:
      - name: nginx-config-volume
        configMap:
          name: nginx-config
      - name: nginx-secret-volume
        secret:
          secretName: nginx-tls-secret