apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: default
  labels:
    tier: backend
data:
  default.conf: |
    server {
        listen 80 default_server;
        listen [::]:80 default_server;
        server_name demo.nginx.raylayadi.com;

        location / {
            return 301 https://$host$request_uri;
        }
    }

    server {
        listen 443 ssl;
        listen [::]:443 ssl;
        server_name demo.nginx.raylayadi.com;
        root /usr/share/nginx/html;
        index index.html;

        location / {
            try_files $uri $uri/ =404;
        }

        ssl on;
        ssl_certificate /etc/nginx/tls/tls.crt;
        ssl_certificate_key /etc/nginx/tls/tls.key;

        error_log  /var/log/nginx/error.log;
        access_log /var/log/nginx/access.log;
    }